basic:
  page_views: 0
  custom_ads: false
  custom_js: false
  custom_domain: true
  private: true
  custom_themes: true
  basic_support: true
  phone_support: false
  price: 900

plus:
  page_views: 1000000
  custom_ads: true
  custom_js: true
  custom_domain: true
  private: true
  custom_themes: true
  basic_support: true
  phone_support: true
  price: 4900

premium:
  page_views: 5000000
  custom_ads: true
  custom_js: true
  custom_domain: true
  private: true
  custom_themes: true
  basic_support: true
  phone_support: true
  price: 24900

maximium:
  page_views: 15000000
  custom_ads: true
  custom_js: true
  custom_domain: true
  private: true
  custom_themes: true
  basic_support: true
  phone_support: true
  price: 74900

optimum:
  page_views: 0
  custom_ads: true
  custom_js: true
  custom_domain: true
  private: true
  custom_themes: true
  basic_support: true
  phone_support: true
  price: 99900
